<?php
require_once('db_connect.php');
require_once('framework.php');
require_once('frontpage.php');
require_once('facades.php');
require_once('register.php');
require_once('supportiveMethods.php');
require_once('income.php');
require_once('expense.php');